### ISSUE TITLE
/data modify entity for markers not working as intended

### ISSUE THREAD

**Issue by Frektip** [Smithed-MC/Radon#13]
It seems like the mod breaks the command `/data modify entity @e[type=marker,limit=1] data... `

The clearest example I can give so far is to install the datapack "[Tool Rack](https://www.planetminecraft.com/data-pack/tool-rack-hang-your-tools-and-weapons/)" made by Noxon (Pause Kawa), which uses that `/data` command to replace the "Item" nbt tag from the marker to an armor stand.

I also try to summon a new marker in the world and try to change it's data nbt with a custom one, but I wasn't able to do it

**Comment by ICY105** [comment]
Fixed in 0.3.3. Apologies for taking so long.
