### ISSUE TITLE
1.19.2 editing marker nbt doesn't work

### ISSUE THREAD

**Issue by thehuglet** [Smithed-MC/Radon#15]
Running Radon on MC version 1.19.2 and trying to set the `data` NBT of a marker doesn't work.

Commands to reproduce:
```mcfunction
summon marker ~ ~ ~ {Tags:[frank]}
data modify entity @e[type=marker,tag=frank,limit=1] data.iq set value 20

data get entity @e[type=marker,tag=frank,limit=1] data
```

Expected `data`:
```hs
{data: {iq: 20}}
```

Actual bugged `data`:
```hs
{data: {}}
```

**Comment by vdvman1** [comment]
I suspect this call to [put](https://github.com/Smithed-MC/Radon/blob/1623728f215b9f475ffc8594d59a1ee74c89f106/src/main/java/dev/smithed/radon/mixin/entity/MarkerEntityMixin.java#L19) isn't merging the compounds

**Comment by ICY105** [comment]
Can you confirm you're using the latest version (0.3.3)? This _should_ be fixed.

**Comment by thehuglet** [comment]
I was actually using `0.3.2` and didn't notice there was another release.

Sorry for the inconvenience, it all works on the latest release. 👍🏻
