### ISSUE TITLE
(Bug) "[STDOUT]: Flag 1" log spam

### ISSUE THREAD

**Issue by Evtema3** [Smithed-MC/Radon#18]
Caused by https://github.com/Smithed-MC/Radon/commit/e3dd3ad9c08f532fa0b559790c8f60d2025c2cb9#diff-7a28e93b457a106d2a0d43d82ce5479f84df355824a117ba3d6a91071b0a7e64R143

**Comment by ICY105** [comment]
fixed in 0.4.1
